### PR TITLE
add support to matic zkevm

### PR DESCRIPTION
**Pull request by MCarlomagno**

### CODE REVIEW

**Comment by biga816** [comment]
When is this PR merged? I think the `dont-merge` label can be removed because Polygon zkEVM is already supported on the Defender dashboard.

**Comment by biga816** [comment]
@zeljkoX @MCarlomagno Do you have a plan to support Polygon zkEVM in this module?
If yes, I would appreciate it if you could merge this PR. I want to use it in my project.

**Comment by MCarlomagno** [comment]
@biga816 Thanks for the heads up on this, I added the dont-merge label due to some issues in the network integration that we already solved. This PR was stale because this repo is being deprecated in favor of [defender-sdk](https://github.com/OpenZeppelin/defender-sdk).

We can merge this PR and release a new version for `defender-client`, but I suggest you to consider moving to `defender-sdk` soon to avoid breaking changes in this client after sunset.

**Review by tirumerla — APPROVED** [review]
lgtm

**Pull request merged**
