### PR TITLE
Add Avax subnet support for DFK

### PR DESCRIPTION
**Pull request by shahnami**

### CODE REVIEW

**Review by ernestognw — APPROVED** [review]
LGTM, just two concerns:

1. I know backend will reject requests from users trying to access DFK subnet, but at least having a note in the code that these are private will be great for me. Perhaps we make `type Network = PublicNetwork | PrivateNetwork` where `PublicNetwork` is what we already have and `PrivateNetwork` is DFK's
2. I do like the idea of keeping a single source for `Network`, but @mok0230 is working on Hedera's sentinels, this may get back to have them separated or at least making `SentinelNetwork = Network | 'hedera'`

**Comment by mok0230** [comment]
Ha @ernestognw, right on the money - I just put this up: https://github.com/OpenZeppelin/defender-client/pull/119

It seems like until something like it gets merged, the integration tests are broken because there's a type mismatch between `Network` in `defender` and `Network` here...

Technically only sentinels can use Hedera at this time. The rest are hidden in the UI, wondering if I should also put up a "Not supported" error in the API? But that ends up being a lot of endpoints...what do you guys think?

**Comment by shahnami** [comment]
> LGTM, just two concerns:
> 
> 1. I know backend will reject requests from users trying to access DFK subnet, but at least having a note in the code that these are private will be great for me. Perhaps we make `type Network = PublicNetwork | PrivateNetwork` where `PublicNetwork` is what we already have and `PrivateNetwork` is DFK's
> 2. I do like the idea of keeping a single source for `Network`, but @mok0230 is working on Hedera's sentinels, this may get back to have them separated or at least making `SentinelNetwork = Network | 'hedera'`

Thanks for the feedback! I think you're right in separating the public and private networks for clarity. We should probably apply the same separation in the defender codebase. As for @mok0230, I don't believe 
`SentinelNetwork = Network | 'hedera'` will do the trick as the tests read from base-client -> Network. Alternatively, Dan, you could add Hedera as part of public network, or create a new `type SentinelNetwork = 'hedera'` and have `export type Network = PublicNetwork | PrivateNetwork | SentinelNetwork` if that's cleaner? Not sure what your thoughts are?

**Comment by spalladino** [comment]
FWIW I don't think it makes sense to have a separate `SentinelNetwork` at the models level, since we'll eventually add Hedera support all across the board.

**Comment by mok0230** [comment]
> Maybe we can combine this validation with the one that takes care of checking if the tenant has access to the network, if it's a custom network?

@spalladino I created this issue to capture the work, but it can't be completed until after Hedera Sentinels gets approved because that's where those properties get added. Or, if we want to up the priority, I could include with my Hedera PR.

https://github.com/OpenZeppelin/defender/issues/2701

**Pull request merged**
